<?php

namespace Core\AccountingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChartmasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartmasterRepository extends EntityRepository
{
	public function findChartmasterByAccountcode($accountcode)
	{
		return $this->getEntityManager()
			->createQuery(
					"SELECT t FROM CoreAccountingBundle:Chartmaster t WHERE t.accountcode = $accountcode"
					)
			->getResult();
	}
}
