<?php

namespace Core\AccountingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodsRepository extends EntityRepository
{
	public function findperiodnowithdate($date)
	{
		$id = $date->format('Y-m-t');
		return $this->getEntityManager()
		->createQuery(
				'SELECT a.periodno
				FROM CoreAccountingBundle:Periods a
				WHERE a.lastdateinperiod = :id'
		)->setParameter('id', $id)
		->getResult();
	}
	
	public function findlastdatewithperiodno($id)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a.lastdateinperiod
				FROM CoreAccountingBundle:Periods a
				WHERE a.periodno = :id'
		)->setParameter('id', $id)
		->getResult();
	}
	
	public function findfirstdatewithperiodno($id)
	{
		$lastdate = $this->getEntityManager()
		->createQuery(
				'SELECT a.lastdateinperiod
				FROM CoreAccountingBundle:Periods a
				WHERE a.periodno = :id'
		)->setParameter('id', $id)
		->getResult();
		$firstdate = $lastdate[0]['lastdateinperiod'];
		return $firstdate->format('Y-m-01');
	}
}
