parameters:
#    core_accounting.example.class: Core\AccountingBundle\Example

services:
#    core_accounting.example:
#        class: %core_accounting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
